# Generated by Django 4.1 on 2022-08-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("email_usuario", models.EmailField(max_length=254)),
                ("nome_usuario", models.TextField(max_length=60)),
                ("telefone_usuario", models.PositiveIntegerField()),
                ("data_nascimento", models.DateField()),
                ("senha_user", models.CharField(max_length=12)),
                ("endereco_user", models.CharField(max_length=30)),
            ],
        ),
    ]
