# Generated by Django 4.1 on 2022-09-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id_autor", models.AutoField(primary_key=True, serialize=False)),
                ("nome_autor", models.TextField(max_length=60)),
            ],
            options={
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nome_categoria", models.CharField(max_length=20)),
                ("desc_categoria", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Editora",
            fields=[
                ("id_editora", models.AutoField(primary_key=True, serialize=False)),
                ("nome_editora", models.CharField(max_length=30)),
                ("cnpj_editora", models.PositiveIntegerField()),
                ("email_editora", models.EmailField(max_length=254)),
                ("senha_editora", models.CharField(max_length=12)),
                ("endereço_editora", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("email_usuario", models.EmailField(max_length=254)),
                ("nome_usuario", models.TextField(max_length=60)),
                ("telefone_usuario", models.PositiveIntegerField()),
                ("data_nascimento", models.DateField()),
                ("senha_user", models.CharField(max_length=12)),
                ("endereco_user", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                ("id_livro", models.AutoField(primary_key=True, serialize=False)),
                ("titulo_livro", models.CharField(max_length=30)),
                ("sinopse_livro", models.CharField(max_length=450)),
                ("numero_paginas", models.PositiveIntegerField()),
                (
                    "categoria",
                    models.ManyToManyField(related_name="livros", to="core.categoria"),
                ),
                (
                    "editora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livro",
                        to="core.editora",
                    ),
                ),
            ],
        ),
    ]
